app/urls.py
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('clientes/listar', views.clientes_lista_api, name='cliente_lista'),
    path('salas/listar', views.salas_lista_api, name='sala_lista'),
    path('peliculas/listar', views.peliculas_lista_api, name='pelicula_lista'),
    path('cines/listar', views.cines_lista_api, name='cine_lista'),

    path('clientes/buscar', views.cliente_busqueda, name='cliente_buscar'),

    path('cines/buscar', views.cine_busqueda, name='cine_buscar'),
    path('salas/buscar', views.sala_busqueda, name='sala_buscar'),
    path('peliculas/buscar', views.pelicula_busqueda, name='pelicula_busqueda'),

    path('clientes/post', views.cliente_post, name='cliente_post'),
    path('clientes/<int:cliente_id>/editar', views.cliente_editar, name='cliente_editar'),
    path('clientes/<int:cliente_id>/actualizar/nombre', views.cliente_editar_nombre, name='cliente_editar_nombre'),
    path('clientes/<int:cliente_id>/eliminar', views.cliente_eliminar, name='cliente_eliminar'),

    path('salas/create', views.sala_crear, name='sala_crear'),
    path('salas/<int:sala_id>/editar', views.sala_editar, name='sala_editar'),
    path('salas/<int:sala_id>/actualizar/tamano', views.sala_actualizar_tamano, name='sala_actualizar_tamano'),
    path('salas/<int:sala_id>/eliminar', views.sala_eliminar, name='sala_eliminar'),

    path('peliculas/create', views.pelicula_crear, name='pelicula_crear'),
    path('peliculas/<int:pelicula_id>/editar', views.pelicula_editar, name='pelicula_editar'),
    path('peliculas/<int:pelicula_id>/actualizar/nombre', views.pelicula_actualizar_nombre, name='pelicula_actualizar_nombre'),
    path('peliculas/<int:pelicula_id>/eliminar', views.pelicula_eliminar, name='pelicula_eliminar'),

    path('registrar',views.registrar_usuario,name='registrar_usuario'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),
]

from django.conf.urls import handler404,handler500
handler404 = "app.views.mi_error_404"
handler500 = "app.views.mi_error_500"

app/forms.py
from django import forms
from .models import *
from datetime import date
import datetime
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ClientePost(forms.Form):
    dni = forms.CharField(max_length=9)
    nombre = forms.CharField(max_length=255)
    apellidos = forms.CharField(max_length=255)
    email = forms.EmailField()

class ClienteEditarForm(forms.Form):
    dni = forms.CharField(max_length=9)
    nombre = forms.CharField(max_length=255)
    apellidos = forms.CharField(max_length=255)
    email = forms.EmailField()

class ClienteActualizarNombreForm(forms.Form):
    nombre = forms.CharField(max_length=255)

class SalaForm(forms.Form):
    TAMANO_CHOICES = [
        ('PE', 'Pequeña'),
        ('ME', 'Mediana'),
        ('GR', 'Grande'),
    ]
    tamano = forms.ChoiceField(choices=TAMANO_CHOICES, label='Tamaño de la Sala')
    cine = forms.ChoiceField(label='Cine')
    empleado = forms.MultipleChoiceField(label='Empleados', required=False)

    def __init__(self, *args, **kwargs):
        cines_disponibles = kwargs.pop('cines_disponibles', [])
        empleados_disponibles = kwargs.pop('empleados_disponibles', [])
        super(SalaForm, self).__init__(*args, **kwargs)
        self.fields['cine'].choices = [(cine['id'], cine['nombre']) for cine in cines_disponibles]
        self.fields['empleado'].choices = [(empleado['id'], empleado['nombre']) for empleado in empleados_disponibles]

class PeliculaForm(forms.Form):
    titulo = forms.CharField(max_length=255)
    director = forms.CharField(max_length=255)
    sinopsis = forms.CharField(widget=forms.Textarea)
    fechaLanzamiento = forms.DateField()
    tiempoProyectada = forms.DurationField(required=False)
    sala = forms.MultipleChoiceField(label='Salas', required=False)

    def __init__(self, *args, **kwargs):
        salas_disponibles = kwargs.pop('salas_disponibles', [])
        super(PeliculaForm, self).__init__(*args, **kwargs)
        self.fields['sala'].choices = [(sala['id'], sala['nombre']) for sala in salas_disponibles]

class BusquedaClienteForm(forms.Form):
    textoBusqueda = forms.CharField(required=False)
    
class BusquedaCineForm(forms.Form):
    direccion = forms.CharField(required=False, label='Dirección')
    telefono = forms.CharField(required=False, label='Teléfono')
    email = forms.EmailField(required=False, label='Email')

class BusquedaSalaForm(forms.Form):
    TAMANO_CHOICES = [
        ('PE', 'Pequeña'),
        ('ME', 'Mediana'),
        ('GR', 'Grande'),
    ]
    tamano = forms.ChoiceField(required=False, choices=TAMANO_CHOICES, label='Tamaño de la Sala')
    cine = forms.CharField(required=False, label='ID del Cine')

class BusquedaPeliculaForm(forms.Form):
    titulo = forms.CharField(required=False, label='Título')
    director = forms.CharField(required=False, label='Director')
    fecha_desde = forms.DateField(required=False, label='Fecha Desde')
    fecha_hasta = forms.DateField(required=False, label='Fecha Hasta')


class RegistroForm(UserCreationForm):
    roles = (
        (2, 'cliente'),
        (3,'empleado'),
        (4,'gerente'),        
    )
    rol = forms.ChoiceField(choices=roles)
    class Meta:
        model = User
        fields = ['username','email','password1','password2','rol']


class LoginForm(forms.Form):
    usuario = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

app/templates/pelicula/actualizar.html
{% extends "principal.html" %}

{% block contenido %}

{% load django_bootstrap5 %}
<form action = "{% url 'pelicula_editar' pelicula.id %}" method = "post"> 
    
    {% csrf_token %} 

    <div class="mb-4">
        <label for="{{ formulario.titulo.id_for_label }}" class="form-label">{{ formulario.titulo.label }}: </label>
        <input  name="{{ formulario.titulo.html_name }}" 
                type="text" 
                class="form-control {% if formulario.titulo.errors %} is-invalid{% elif formulario.is_bound %} is-valid{% endif %}" 
                id="{{ formulario.titulo.id_for_label }}"
                maxlength="{{ formulario.titulo.field.max_length }}"
                {% if formulario.titulo.field.required %}
                    required
                {% endif %}
                value="{% spaceless %}
                       {% if formulario.is_bound%}
                            {{ formulario.titulo.value }}
                       {% elif pelicula %}
                            {{ formulario.titulo.value }}
                       {% endif %} 
                       {% endspaceless %}"
        />
        {% if formulario.titulo.help_text %}
        <div class="form-text">
            {{ formulario.titulo.help_text }}
        </div>
        {% endif %}
        <div class="invalid-feedback">
            {% for error in formulario.titulo.errors %} 
                {{ error }}
            {% endfor %}
        </div>
    </div>

    <div class="mb-4">
        <label for="{{ formulario.director.id_for_label }}" class="form-label">{{ formulario.director.label }}: </label>
        <textarea name="{{ formulario.director.html_name }}" 
                  class="form-control {% if formulario.director.errors %} is-invalid{% elif formulario.is_bound %} is-valid{% endif %}" 
                  id="{{ formulario.director.id_for_label }}"
                  >{% spaceless %}
                        {% if formulario.is_bound%}
                            {{ formulario.director.value }}
                        {% elif pelicula %}
                            {{ formulario.director.value }}
                        {% endif %} 
                        {% endspaceless %}</textarea>
        <div class="invalid-feedback">
            {% for error in formulario.director.errors %} 
                {{ error }}
            {% endfor %}
        </div>
    </div>

    <div class="mb-4">
        {% bootstrap_field formulario.fechaLanzamiento show_label=True %}
        <div class="invalid-feedback">
            {% for error in formulario.fechaLanzamiento.errors %} 
                {{ error }}
            {% endfor %}
        </div>
    </div>


    <div class="mb-4">
        {% bootstrap_field formulario.sala show_label=True %}
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>

</form> 


{% endblock %}

app/templates/pelicula/actualizar_titulo.html
{% extends "principal.html" %}

{% block contenido %}
<h2>Actualizar Título de la Película</h2>

<form method="post">
    {% csrf_token %}
    {{ formulario.titulo.label_tag }} {{ formulario.titulo }}
    <button type="submit" class="btn btn-primary">Actualizar Título</button>
    <a href="{% url 'pelicula_lista' %}" class="btn btn-secondary">Cancelar</a>
</form>

{% endblock %}

app/templates/pelicula/busqueda_avanzada_datepicker.html
{% extends "principal.html" %}

{% block cabecera %}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>
{% endblock %}

{% block contenido %}
{% load django_bootstrap5 %}
    <form action = "{% url 'pelicula_buscar' %}" method = "GET"> 
        
        {% csrf_token %}

        <div class="mb-4">
            {% bootstrap_field formulario.titulo show_label=True %}
        </div>

        <div class="mb-4">
            {% bootstrap_field formulario.director show_label=True %}
        </div>

        <div class="mb-4">
            {% bootstrap_field formulario.fecha_desde show_label=True %}
            <div class="invalid-feedback">
                {% for error in formulario.fecha_desde.errors %} 
                    {{ error }}
                {% endfor %}
            </div>
        </div>

        <div class="mb-4">
            {% bootstrap_field formulario.fecha_hasta show_label=True %}
            <div class="invalid-feedback">
                {% for error in formulario.fecha_hasta.errors %} 
                    {{ error }}
                {% endfor %}
            </div>
        </div>

        {% bootstrap_button "Enviar" button_type="submit" button_class="btn-primary" %}
      
    </form> 
{% endblock %}

app/templates/pelicula/create.html
{% extends "principal.html" %}

{% block contenido %}
<h2>Crear Película</h2>

<form method="post">
    {% csrf_token %}
    {{ formulario.as_p }}
    <button type="submit" class="btn btn-primary">Crear Película</button>
</form>

{% endblock %}

app/templates/pelicula/editar.html
{% extends "principal.html" %}

{% block contenido %}
<h2>Editar Película</h2>

<form method="post">
    {% csrf_token %}
    
    <div class="form-group">
        <label for="id_titulo">Título de la Película</label>
        {{ formulario.titulo }}
    </div>
    
    <div class="form-group">
        <label for="id_director">Director</label>
        {{ formulario.director }}
    </div>
    
    <div class="form-group">
        <label for="id_sinopsis">Sinopsis</label>
        {{ formulario.sinopsis }}
    </div>
    
    <div class="form-group">
        <label for="id_fechaLanzamiento">Fecha de Lanzamiento</label>
        {{ formulario.fechaLanzamiento }}
    </div>
    
    <div class="form-group">
        <label for="id_tiempoProyectada">Tiempo Proyectada</label>
        {{ formulario.tiempoProyectada }}
    </div>
    
    <div class="form-group">
        <label for="id_sala">Sala(s)</label>
        {{ formulario.sala }}
        <small class="form-text text-muted">
            Mantén pulsada la tecla control para seleccionar varias salas
        </small>
    </div>
    
    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    <a href="{% url 'pelicula_lista' %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock %}

app/templates/pelicula/lista.html
{% extends "principal.html" %}

{% block header %}
    <h1>Lista de Películas</h1>
{% endblock %}

{% block contenido %}
    {% for pelicula in peliculas_mostrar %}
        {% include 'pelicula/pelicula.html' %}
    {% empty %}
        <p>No hay películas disponibles.</p>
    {% endfor %}
{% endblock %}

app/templates/pelicula/lista_api.html
{% extends "principal.html" %}

{% block contenido %}
<h2>Lista de Películas</h2>

<table class="table">
    <thead>
        <tr>
            <th>Título</th>
            <th>Director</th>
            <th>Fecha de Lanzamiento</th>
            <th>Sinopsis</th>
            <th>Tiempo Proyectada</th>
            <th>Salas</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for pelicula in peliculas_mostrar %}
        <tr>
            <td>{{ pelicula.titulo }}</td>
            <td>{{ pelicula.director }}</td>
            <td>{{ pelicula.fechaLanzamiento }}</td>
            <td>{{ pelicula.sinopsis }}</td>
            <td>{{ pelicula.tiempoProyectada }}</td>
            <td>
                {% for sala in pelicula.sala %}
                    {{ sala.tamano }}<br>
                {% endfor %}
            </td>
            <td>
                <a href="{% url 'pelicula_editar' pelicula.id %}" class="btn btn-primary">Editar</a>
                <a href="{% url 'pelicula_eliminar' pelicula.id %}" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app/templates/pelicula/lista_busqueda.html
{% extends "pelicula/lista.html" %}

{% block busqueda %}
    <h2 class="display-5">{{ texto_busqueda|linebreaksbr }}</h2>
{% endblock %}

app/templates/pelicula/pelicula.html
<h2>{{ pelicula.titulo|title }}</h2>
<p>Director: {{ pelicula.director|capfirst }}</p>
<p>Sinopsis: {{ pelicula.sinopsis|default:"Sin sinopsis disponible." }}</p>
<p>Estrenada hace: {{ pelicula.fechaLanzamiento|timesince}}</p>
<p>Tiempo Proyectado: {{ pelicula.tiempoProyectada|default_if_none:"No hay un tiempo de proyección especificado para esta película" }}</p>
<hr>

<div class="row btn-group">
    <div class="mb-2">
        <button type="button" class="btn btn-outline-primary">
            <a href="{% url 'pelicula_editar' pelicula.id %}">
                <span>{% bs_icon 'pencil' %}</span>
            </a>
        </button>
    </div>
    <div class="mb-2">
        <form action="{% url 'pelicula_eliminar' pelicula.id %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger" onclick="return eliminar();" type="submit">
                <span>{% bs_icon 'trash' %}</span>
            </button>
        </form>
    </div>
</div>

app/templates/pelicula/read.html
{% extends "principal.html" %}
{% block header %}
    <h1>Buscar Película</h1>
{% endblock %}

{% block contenido %}
<form action="{% url 'pelicula_buscar' %}" class="d-flex mt-3" role="search" method="GET">
    <input name="textoBusqueda" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-light btn-outline-dark">Buscar</button>
</form>
{% endblock %}